import Head from "next/head";

const HtmlHead = () => {
  return (
    <Head>
      <title>Con Sazon</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
export default HtmlHead;
